### ISSUE TITLE
Change text when a unit looses men if they dont receive upkeep.

### ISSUE THREAD

**Issue by Chikitek** [artyomtrityak/Atlantis#22]
If a unit does not receive the required monthly upkeep it has a chance to just die. And it clearly says that they starve in report. It doesn't make sense that recruited people just die if they are not paid. They would obviously desert or resign (pick any) long before that.

Suggested text:
Unit (xx) failed to receive enough upkeep, 18 deserted.

**Comment by artyomtrityak** [comment]
Sometimes they just starve :( I was thinking about this for some time and it looks like starving is okay. Like you send people to the desert and they died because no food.
