### ISSUE TITLE
Rules neglect to mention that you can't steal from guards/monsters

### ISSUE THREAD

**Issue by sparr** [artyomtrityak/Atlantis#23]
https://github.com/artyomtrityak/Atlantis/blob/master/runorders.cpp#L383-L388

probably deserves clarification near here: https://github.com/artyomtrityak/Atlantis/blob/master/genrules.cpp#L3749-L3752

**Comment by artyomtrityak** [comment]
https://github.com/artyomtrityak/Atlantis/pull/25
