### ISSUE TITLE
Flag skill increases in report/template

### ISSUE THREAD

**Issue by sparr** [artyomtrityak/Atlantis#37]
It would be helpful and avoid having to refer to previous turns' reports if units with skill increases through usage were flagged in some way.

Maybe instead of `combat [COMB] 1 (35)` it could be `combat [COMB] 1 (35)(+5)` or similar?

**Comment by artyomtrityak** [comment]
it might break parsers, can you double check that ALH and Advisor work for with that?

**Comment by artyomtrityak** [comment]
closing for now, not going to work due to other more important stuff and not sure it is needed.
