### ISSUE TITLE
Ships can cross land bridges by getting a new number

### ISSUE THREAD

**Issue by sparr** [artyomtrityak/Atlantis#42]
I have heard but not confirmed that it is possible to move a ship across a land bridge by merging fleets and/or giving the ship to another unit, which causes the "which side did I enter from" information to be lost. If this is true then it is a bug in the enforcement of ALLOW_TRIVIAL_PORTAGE (off).

**Comment by artyomtrityak** [comment]
it is true, this is known, i did not want to publicly announce this due to use of the bug but it is true. Will be fixed.

**Comment by artyomtrityak** [comment]
fixed
