### ISSUE TITLE
Allow allies to muster for battle from adjacent hex without a scout

### ISSUE THREAD

**Issue by sparr** [artyomtrityak/Atlantis#47]
Currently if my ally and I have neighboring hexes, we won't assist each other in combat unless we park a unit in each others' territory. That seems silly and counterintuitive. If I can signal my own units in the adjacent hex to assist, why can't I send the same signal to my allies' units?

Put another way... I want my units and my allies' units to behave as if they belong to the same army.

Feature request is to make this behave the same whether I have a unit in the attack hex or not.

**Comment by artyomtrityak** [comment]
Sorry, i do not think it will be a good addition to the game.
